name: Android Build

# 触发条件
on:
  # 手动启动
  workflow_dispatch:
  
  # 提交代码后触发
  push:
    branches:
      - main  # 你可以根据需要修改为其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  # 使用 adoptopenjdk 作为 JDK 发行版
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30'  # 你可以根据需求更改 SDK 版本

      - name: Build the project
        run: |
          chmod +x gradlew  # 让 gradlew 脚本可执行
          ./gradlew assembleRelease  # 执行构建命令，修改为适合你项目的命令

      - name: Upload APK to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'app/build/outputs/apk/release/*.apk'  # 适当修改为 APK 文件路径
          tag: 'v${{ github.run_number }}'  # 使用构建号生成版本标签
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
