name: Android Release Build
 
on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.0)'
        required: true 
        type: string
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
 
      - name: 验证Secrets 
        run: |
          [ -n "$KEYSTORE_BASE64" ] || { echo "::error::缺少KEYSTORE_BASE64"; exit 1; }
          [ -n "$KEYSTORE_PASSWORD" ] || { echo "::error::缺少KEYSTORE_PASSWORD"; exit 1; }
          [ -n "$KEY_ALIAS" ] || { echo "::error::缺少KEY_ALIAS"; exit 1; }
          [ -n "$KEY_PASSWORD" ] || { echo "::error::缺少KEY_PASSWORD"; exit 1; }
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
 
      - name: 设置JDK 
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
 
      - name: 构建APK 
        run: |
          echo "$KEYSTORE_BASE64" | base64 -di > keystore.jks  
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=keystore.jks  \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD"  \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS"  \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD" 
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
 
      - name: 准备发布文件 
        run: |
          mkdir -p release_assets
          cp app/build/outputs/apk/release/*.apk release_assets/
          cp app/build/outputs/mapping/release/mapping.txt  release_assets/ || true
 
      - name: 创建GitHub Release 
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: v${{ inputs.version  }}
          name: Release v${{ inputs.version  }}
          body: "自动构建版本 ${{ inputs.version  }}"
          files: |
            release_assets/*.apk
            release_assets/mapping.txt 
          draft: false 
          prerelease: false 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
